### ISSUE TITLE
Repository contribution guidelines section

### ISSUE THREAD

**Issue by jelster** [InRule/Samples#3]
Contribution guidance is very basic currently - they could use a separate section in the repos' README. Specifics are up to @InRule/engineering, but this might also be a good opportunity as well to set contributor's expectations re: response times and feedback on PR's. For reference, here is the [VS Code contrib guidelines](https://raw.githubusercontent.com/Microsoft/vscode/master/README.md):

## Contributing

If you are interested in fixing issues and contributing directly to the code base,
please see the document [How to Contribute](https://github.com/Microsoft/vscode/wiki/How-to-Contribute), which covers the following:

* [How to build and run from source](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source)
* [The development workflow, including debugging and running tests](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#development-workflow)
* [Coding Guidelines](https://github.com/Microsoft/vscode/wiki/Coding-Guidelines)
* [Submitting pull requests](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#pull-requests)

Please see also our [Code of Conduct](CODE_OF_CONDUCT.md).

**Comment by emcowen40** [comment]
Thank you for submitting the ticket! We've added contribution guidelines to the repo.
